// <auto-generated />
namespace DASL_Import_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoomTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201511070157220_RoomTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
