// <auto-generated />
namespace DASL_Import_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StaffMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StaffMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201602120248418_Staff-Members"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
